name: Deploy Sphinx Site to GitHub Pages

on:
  push:
    branches: [ "main" ]

runs:
  using: "docker"
  image: "../.devcontainer/Dockerfile"

jobs:
  build:
    steps:
      - uses: actions/checkout@v4
      - name: Make static files
        run: make html

      - name: Create artifact from static files
        uses: actions/upload-pages-artifact
        with:
          path: ./build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
