name: Deploy Sphinx Site to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx
          python -m pip install myst-nb
          python -m pip install pydata-sphinx-theme

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Make static files
        run: make html

      - name: Create artifact from static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write  # Add this line to grant the necessary permission
      contents: read  # You may need other permissions as well
    steps:
      - name: Deploy artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
