name: Deploy Sphinx Site to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: sphinxdoc/sphinx
    steps:
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install myst-nb
          python -m pip install pydata-sphinx-theme

      - name: Checkout
        uses: actions/checkout@main
        
      - name: Make static files
        run: make html

      - name: Create artifact from static files
        uses: actions/upload-pages-artifact@main
        with:
          path: ./build/html

  deploypoopy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write  # Required for deploying to GitHub Pages
      contents: read  # You may need other permissions as well
    steps:
      - name: Deploy artifact to GitHub Pages
        uses: actions/deploy-pages@main
